name: CICD
on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: '14.x 16.x'

    - name: Install dependencies
      run: npm install

    - name: Build Vue.js project
      run: npm run build

    - name: Verify compiled files
      run: |
        if [ -d "dist" ]; then
          echo "Compilation succeeded."
        else
          echo "Compilation failed."
          exit 1
        fi